# Generated by Django 3.2.9 on 2021-12-09 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_auto_20211209_1833'),
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_campaign', to='campaigns.campaign'),
        ),
    ]
