# Generated by Django 3.2.9 on 2021-12-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
