# Generated by Django 3.2.9 on 2021-12-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20211207_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='byline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='funded',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
